/** @externs */
/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from /home/circleci/.cache/bazel/_bazel_circleci/f16e36219ef33c22efc2ad20f3e3775c/execroot/ngrx/modules/effects/src/lifecycle_hooks.ts:
/** @const */
var ngrx$modules$effects$src$lifecycle_hooks = {};
/**
 * @record
 * @struct
 */
ngrx$modules$effects$src$lifecycle_hooks.OnIdentifyEffects = function() {};

/**
 * \@description 
 * String identifier to differentiate effect instances.
 * @return {?}
 */
ngrx$modules$effects$src$lifecycle_hooks.OnIdentifyEffects.prototype.ngrxOnIdentifyEffects = function() {};
/**
 * @record
 * @struct
 */
ngrx$modules$effects$src$lifecycle_hooks.OnRunEffects = function() {};

/**
 * \@description 
 * Method to control the lifecycle of effects.
 * @param {?} resolvedEffects$
 * @return {?}
 */
ngrx$modules$effects$src$lifecycle_hooks.OnRunEffects.prototype.ngrxOnRunEffects = function(resolvedEffects$) {};
/**
 * @record
 * @struct
 */
ngrx$modules$effects$src$lifecycle_hooks.OnInitEffects = function() {};

/**
 * \@description 
 * Action to be dispatched after the effect is registered.
 * @return {?}
 */
ngrx$modules$effects$src$lifecycle_hooks.OnInitEffects.prototype.ngrxOnInitEffects = function() {};
